spring:
  application:
    name: discodeit
    version: 1.0.0
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: info

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage